### PR TITLE
Metadata extractor and Maven updates (saxon95 branch)

### PR DESCRIPTION
**Pull request by sharwell**
This pull request is the **saxon95** version of pull request #118. However, it uses a different strategy from previous work, which I have found is much more suited to the long-term maintenance of parallel working branches in Git.

Rather than continuing to cherry-pick commits, this change _merges_ **saxon94** &rarr; **saxon95**. Prior to the discontinuation of the **saxon94** branch (if that ever happens), changes can be made in the **saxon94** branch and then the branch is merged into the **saxon95** branch. This dramatically simplifies the long-term maintenance of the two releases.

This change lists many commits, but in reality only has the following impacts:
1. 69c516fbe9bc19b1ad17d896e1f052d44e239a05 merges the existing **saxon94** branch into the **saxon95** branch, creating a reference point for future work. The _only_ change to the **saxon95** code as a result of this is moving one field declaration down two lines so it matches in both branches.
2. 02aea10ab9cca02950ad501d58788c34d37ee3cf applies the changes in pull #118 to the **saxon95** branch. The `<artifactId>` for this branch is `xmlcalabash-saxon95`.

### CODE REVIEW

**Comment by sharwell** [comment]
Please note that after I sent this pull request, I updated it via force-push to change the `artifactId` from `xmlcalabash` to `xmlcalabash-saxon95`, allowing for a co-release of both the **saxon94** and **saxon95** branches with the same version number.

**Comment by ndw** [comment]
Slightly surprised you combined the MetadataExtractor changes and the Maven updates into a single pull request.

I don't see the 2.7.0 release of MetadataExtractor yet...

**Comment by sharwell** [comment]
I would normally make that a separate pull request, but the changes were very small and the current code didn't compile against the version of MetadataExtractor which is readily available through Maven.

**Comment by ndw** [comment]
Ah. I didn't realize 2.7.0 snapshots are what's readily available. Sigh. I guess I'll move forward then. I did check and both requests merged cleanly.

**Pull request merged**
