### PR TITLE
add UnparsedTextURIResolver in XSLT.java (need to have get/setUnparsedTe...

### PR DESCRIPTION
**Pull request by innovimax**
...xtURIResolver on com.xmlcalabash.core.XProcRuntime)

### CODE REVIEW

**Comment by innovimax** [comment]
related to http://code.google.com/p/xmlcalabash/issues/detail?id=161

**Comment by innovimax** [comment]
Well in fact I didn't forgot : that written in the title " (need to have get/setUnparsedTextURIResolver on com.xmlcalabash.core.XProcRuntime)"

**Comment by ndw** [comment]
Well, uh, have you implemented those bits too? Would you like to make them part of the patch? :-)

**Comment by innovimax** [comment]
There are just dummy getter and setter of a private object, aren't they?

**Comment by ndw** [comment]
Nudge: I sent you a complete patch in email to test. Please let me know if it works.

**Comment by ndw** [comment]
Impatiently assuming my patch works. :-)

Let me know if I'm wrong!

**Pull request closed without merging**
