### PR TITLE
make getCompressedSize and getSize from ZipEntry working again

### PR DESCRIPTION
**Pull request by OSwoboda**
ZipEntry size/compressedSize = −1 for compressed entries

Switched from ZipInputStream to ZipFile to make it work.

### CODE REVIEW

**Comment by ndw** [comment]
Can you tell me more about what bug this fixes? I created a zip file and ran unzip on it, I got:

```
 <c:file compressed-size="4446"
           size="14844"
           name="build.gradle"
           date="2015-10-23T12:42:38.000+09:00"/>
```

It looks like size and compressed-size are working...

**Comment by OSwoboda** [comment]
If you're using this gist https://gist.github.com/gimsieke/209341895897cad40611 the size and compressed size aren't working.

**Comment by ndw** [comment]
Oh, I see. If the inputs are being streamed then there's no way to know the size.

Having to write them to disk seems like potentially a lot of overhead. I wonder if this needs to be optional at the very least.

**Comment by ndw** [comment]
Fixed, I believe. Sorry for how long it took.

**Pull request closed without merging**
