### PR TITLE
Use HttpClient for all HTTP requests and abstract java.io.File operations

### PR DESCRIPTION
**Pull request by catch-point**
This change provides an abstraction layer to many of the java.net.URL and java.io.File operations. Most importantly it allows HttpClient to seamlessly authenticate to any HTTP host by using the XProcRuntime HttpClient for all HTTP operations. This also enables HTTP support for POST'ing results of p:xsl-formatter and p:store. It also allows p:store to store data to directories (with a generated filename, using the media-type to determine file extension).

When embedded this even allows interception of file system operations that can be used to selectively block access or provide a virtual file system over HTTP or WebDav.

The following steps are effected by this change:

p:http-request when a non-http/https: href URI is provided
p:data
p:document when a file: href URI is provided
p:xinclude when reading text
p:xsl-formatter
p:store
pxf:delete
pxf:directory-list
pxf:copy
pxf:head
pxf:mkdir
pxf:move
pxf:tail
pxf:touch
cx:css-formatter
cx:java-properties
pxp:unzip
pxp:zip

### CODE REVIEW

**Comment by ndw** [comment]
I'll see if I can get this in the next release. Just have to think it through a bit.

**Comment by catch-point** [comment]
Let me know if there is anything I can do. I am most interested in getting all HTTP requests to go through the provided HttpClient. I don't want to use java.net.URLConnection to load anything.

**Comment by ndw** [comment]
How wedded are you to the GPL? I'd prefer something more liberal.

**Comment by catch-point** [comment]
I grant Norman Walsh a BSD license on these changes and any past changes we have made to calabash. We like any popular OSI-approved license.

**Comment by catch-point** [comment]
Have you had a chance to review this?

Thanks,
James

**Comment by ndw** [comment]
Ok. I've applied this change. Running tests now.

N.B. For anyone who comes along later, this patch doesn't apply cleanly to the saxon-94 branch and I have decided not to port it to Saxon 9.4. In principal, it could be done, but it would require some manual effort and I'm not inclined to do it now.

**Comment by ndw** [comment]
FYI: I needed to add the following patches; the JDK 1.7 patch is actually untested at the moment:

```
diff --git a/src/com/xmlcalabash/io/FileDataStore.java b/src/com/xmlcalabash/io/FileDataStore.java
index 8cb2f1a..d433f9e 100644
--- a/src/com/xmlcalabash/io/FileDataStore.java
+++ b/src/com/xmlcalabash/io/FileDataStore.java
@@ -20,6 +20,8 @@

 package com.xmlcalabash.io;

+import com.xmlcalabash.core.XProcException;
+
 import java.io.BufferedInputStream;
 import java.io.File;
 import java.io.FileFilter;
@@ -148,6 +150,11 @@ public class FileDataStore implements DataStore {
        URI uri = baseURI.resolve(href);
        if ("file".equalsIgnoreCase(uri.getScheme())) {
            File file = new File(uri);
+
+            if (!file.canRead()) {
+                throw XProcException.stepError(12);
+            }
+
            if (file.isDirectory()) {
                for (File f : listAcceptableFiles(file, accept)) {
                    String type;
diff --git a/src/com/xmlcalabash/io/URLDataStore.java b/src/com/xmlcalabash/io/URLDataStore.java
index 85394d5..c5c5f3c 100644
--- a/src/com/xmlcalabash/io/URLDataStore.java
+++ b/src/com/xmlcalabash/io/URLDataStore.java
@@ -24,6 +24,7 @@ import java.io.FileNotFoundException;
 import java.io.IOException;
 import java.io.InputStream;
 import java.io.OutputStream;
+import java.lang.reflect.Method;
 import java.net.MalformedURLException;
 import java.net.URI;
 import java.net.URL;
@@ -78,7 +79,17 @@ public class URLDataStore implements DataStore {
        try {
            String type = connection.getContentType();
            URI id = URI.create(connection.getURL().toExternalForm());
-           long len = connection.getContentLengthLong();
+            long len = 0;
+
+            // Call getContentLengthLong if it's available
+            try {
+                Method lenMethod = connection.getClass().getDeclaredMethod("getContentLengthLong");
+                lenMethod.invoke(connection.getClass());
+            } catch (Exception e) {
+                // Whatever...
+                len = connection.getContentLength();
+            }
+
            handler.load(id, type, stream, len);
        } finally {
            stream.close();
```

**Comment by catch-point** [comment]
I think that should be "lenMethod.invoke(connection);".

**Pull request merged**
